database:
  host: localhost
  port: 5432
  username: dart
  password: dart
  databaseName: dart_test
translateEngines:
  - name: cloudoptai
  - name: deepl
    authKey: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
