database:
  host: localhost
  port: 5432
  username: dart
  password: dart
  databaseName: dart_test
translateEngines:
  - name: caiyun
    token:
    requestId: translate_openapi
  - name: cloudoptai
  - name: deepl
    authKey:
  - name: youdao
    appKey:
    appSecret:
