name: translate_openapi
description: An translate open api.
version: 0.0.1
author: LiJianying <lijy91@foxmail.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1

  translate_client:
    path: ../dart_pkgs/packages/translate_client
  translate_engine_cloudoptai:
    path: ../dart_pkgs/packages/translate_engine_cloudoptai
  translate_engine_deepl:
    path: ../dart_pkgs/packages/translate_engine_deepl

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0